name: ci 

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust Nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly 
        override: true
        profile: minimal

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo build
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Install Dependencies
      run: cargo fetch

    - name: Check Formatting
      run: cargo fmt -- --check

    - name: Run Linter
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build Project
      run: cargo build

    - name: Run Tests
      run: cargo test --all-features